### ISSUE TITLE
indication of file locations

### ISSUE THREAD

**Issue by Penderis** [Semantic-Org/Semantic-UI-Docs#10]
Hi, thank you for your framework, I as a newbie trying to follow a "semantic workflow" just do not know where to ever place the files this is also the case with semantic ui, I get these things build ect but am completely unsure where to place them within a project structure, such as when I build semantic ui via gulp also , could you update docs to reflect a fake project structure indicative of file location ect which files are truly used if I go with adding semantic less files to a current gulp project? hope this is clear.

**Comment by onetom** [comment]
I will have a flight in 9 hours and I wanted the SUI docs offline.
I'm not a beginner, but instead it's late and I'm a bit tired.
This approximates a beginner user well imho, and docs should be clear for them too.

The "How to Use" section should have a proper transcript of what should I do, which I could just copy-paste and run as a regular user who already have `npm`.

I tried to execute the `docpad install eco`, but it shitted into the root of my home, since you haven't said anything about the purpose of the installation, neither recommended a directory to run it from.

I looked into the `package.json` and I see it has these plugins mentioned in there too, so I suspect this part of the doc is simply just stale.

Then I tried `npm install` in the Semanti-UI-Docs folder and followed the `gulp build-docs` as the README suggests but I just got a
```
[00:26:27] Local gulp not found in ~/r/Semantic-Org/Semantic-UI-Docs
```

I guessed you meant `./Semantic-UI` by `./ui` so I ran `npm install && gulp build-docs` there.
That created stuff, like:

```
...
[gulp] Created: ../docs/out/dist/components/dimmer.js
[gulp] Created: ../docs/out/src/definitions/behaviors/form.js
...
[gulp] Created: ../docs/out/src/themes/twitter/elements/button.variables
```

Next:

```
onetom@retinatom ~/r/S/Semantic-UI-Docs> docpad run
...
info: DocPad listening to http://127.0.0.1:9778/ on directory /Users/onetom/r/Semantic-Org/Semantic-UI-Docs/out
info: Generating...
warning: A warning occured:

Error: Rendering the extension "eco" to "html" on "/Users/onetom/r/Semantic-Org/Semantic-UI-Docs/server/documents/hotfix.html.eco" didn't do anything.
Explanation here: http://docpad.org/extension-not-rendering
  at DocPad.warn (/Users/onetom/r/Semantic-Org/Semantic-UI-Docs/node_modules/docpad/out/lib/docpad.js:2238:56)
...
```

I could keep on guessing, but can someone who understands all this from the top of their head provide a better step by step installation instruction, please?

Wouldn't it be better use of my time if I could actually contribute to the documentation, instead of trying to figure out how to even compile it?

I would expect something like:

```
SEM=~/Semantic-Org    # adjust this to your personal environment

npm install -g gulp   # or maybe we can just use `npm run gulp -- build-docs` if we need local gulp anyway?

mkdir $SEM
cd $SEM
git clone https://github.com/Semantic-Org/Semantic-UI.git
git clone https://github.com/Semantic-Org/Semantic-UI-Docs.git
cd $SEM/Semantic-UI
npm install
gulp build-docs
cd $SEM/Semantic-UI-Docs
docpad run   # or rather `npm run docpad` maybe?
...
```

**Comment by onetom** [comment]
My example also made me wonder why did u use such a naming scheme for your repos if u actually expect them to be checked out with short names... :/ I see there is already a tendency to drop the `Semantic-` prefix for the component repos, so I guess this process was simply not finished.

Btw, as I see the Semantic-UI github org is not taken; wouldn't it be more "idiomatic" to use that, so you can have

* https://github.com/semantic-ui/all vs https://github.com/Semantic-Org/Semantic-UI
* https://github.com/semantic-ui/less
* https://github.com/semantic-ui/css
* https://github.com/semantic-ui/sass

* https://github.com/semantic-ui/grid vs instead of https://github.com/Semantic-Org/UI-Grid
* https://github.com/semantic-ui/docs
* https://github.com/semantic-ui/api
* https://github.com/semantic-ui/learn vs https://github.com/Semantic-Org/Learn-Semantic
* https://github.com/semantic-ui/legacy vs https://github.com/Semantic-Org/Semantic-UI-Legacy

* https://github.com/semantic-ui/angular
* https://github.com/semantic-ui/ember
* https://github.com/semantic-ui/meteor

* https://github.com/semantic-ui/pt-br
* https://github.com/semantic-ui/nl

etc... just to show how unlikely to have any naming conflict.
I noticed there is a UI-Ad but according to http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes there is no such 2 letter language code as AD ;)

Looks like somebody on the team loves to be overly specific and type a lot just to look busy. Maybe has some Java background... ;P

I know such renames would affect quite a lot of things, but would also make all the build scripts clearer and easier to read...

**Comment by jlukic** [comment]
Assuming two siblings folders

1) UI folder `./ui`
2) Docs folder `./docs`

* Clone both repos to respective folders
* `npm install` in both directories
* `cd ui/`  `gulp build-docs` (builds files to docs)
* `cd ../docs` `docpad run`

Should be in business

**Comment by GabrielLacerda** [comment]
onetom and jlukic thanks guys,these tip's worked for me...
i'm going today create a script to execute these commands,
expect good news boys haha.
